version: '2'
    
services:
    
  hello-world-app:
    build: 
      context: .
      dockerfile: ./hello-world-app/Dockerfile
    ports:
      - "3333:9999"
    environment:
      - HANA_UID=${HANA_UID}
      - HANA_PWD=${HXE_MASTER_PASSWORD}
      - HANA_SERVERNODE=${HANA_SERVER} 

  sqlpad:
    image: sqlpad/sqlpad
    volumes:
      - sqlpad:/var/lib/sqlpad
    ports:
      - "8899:3000"
          
  hxehost:
    image: store/saplabs/hanaexpress:2.00.036.00.20190223.1
    hostname: hxe
    volumes:
      - hana-express:/hana/mounts
    command: --agree-to-sap-license --master-password ${HXE_MASTER_PASSWORD}
    
volumes:
  hana-express:
  sqlpad: